### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Charles-Kaminski** [tkrabel/bamboolib#44]
### Environment

* Operating System: Ubuntu 22.04.1 LTS
* Python Version: Python 3.7.13
* How did you install bamboolib: Conda

### Description of Issue

* What did you expect to happen?  I tried to install bamboolib from a fresh ubntu 22.04.01 installation using the conda instructions provided
* What happened instead? The installation failed

### Reproduction Steps

1.  Install a fresh installation of the latest Ubuntu and update
2. Install Anaconda and update
3. Follow the instruction for Bamboolib installation via conda found here : https://docs.bamboolib.8080labs.com/documentation/how-tos/installation-and-setup/install-bamboolib#installation-with-anaconda-virtual-environment
4. Note that the following step returns an error: python -m bamboolib install_nbextensions

The error is as follows:  

Trying to install bamboolib nbextension...
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/bamboolib/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/bamboolib/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/bamboolib/__main__.py", line 38, in <module>
    install_nbextensions()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/bamboolib/setup/_extensions.py", line 42, in install_nbextensions
    nbextensions.install_nbextension_python(extension, user=True)
  File "/home/ubuntu/anaconda3/envs/bamboolib/lib/python3.7/site-packages/notebook/nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/home/ubuntu/anaconda3/envs/bamboolib/lib/python3.7/site-packages/notebook/nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "/home/ubuntu/anaconda3/envs/bamboolib/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 38, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'plotlywidget'

...

### What steps have you taken to resolve this already?

...

### Anything else?

...

**Comment by fwetdb** [comment]
You can fix this via also installing the `plotlywidget` module via conda which might be needed for enabling the plotly figure extensions

**Comment by Charles-Kaminski** [comment]
No such module.  Is there a particular channel to find the plotlywidget module in?  

~~~~

PackagesNotFoundError: The following packages are not available from current channels:

  - plotlywidget

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

**Comment by fwetdb** [comment]
I do not know. You can ask this question to the plotly.py team. They are the experts on this.

Otherwise, you might want to consider to install plotlywidget via pip (and mix the installations) or use pip in general instead of conda.

What do you think?
